---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    uses: ./.github/workflows/00_linter.yaml

  test:
    uses: ./.github/workflows/01_test.yaml
