---
name: Renovate

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 5,8 * * *"
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
      RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
      RENOVATE_TOKEN: "${{ secrets.RENOVATE_TOKEN }}"  # PAT with `repo` and `workflow` permission
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Validate config
        uses: docker://ghcr.io/renovatebot/renovate:37.349.0
        with:
          args: renovate-config-validator --strict
      - name: Renovate
        uses: docker://ghcr.io/renovatebot/renovate:37.349.0
        with:
          args: renovate
