---
name: Renovate

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 5,8 * * *"
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
      RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
      RENOVATE_TOKEN: "${{ secrets.RENOVATE_TOKEN }}"  # PAT with `repo` and `workflow` permission
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Validate config
        uses: docker://ghcr.io/renovatebot/renovate:37.412.2
        with:
          args: renovate-config-validator --strict
      - name: Renovate
        uses: docker://ghcr.io/renovatebot/renovate:37.412.2
        with:
          args: renovate
